### ISSUE TITLE
Bazaar Cauldron Always Gives 2 Items

### ISSUE THREAD

**Issue by Vallith** [Flyingcomputer/ExchangeChanges-RoR2#4] opened 2022-03-16 07:56 UTC
When using the bazaar cauldrons - it always seems to give you double what you should get. If I print one legendary, it will shoot out 2. This happens even if I do it slowly.

**Comment by Flyingcomputer** [comment] 2022-03-16 08:21
Duplicate of #3

**Closed as completed by Flyingcomputer** 2022-03-16 08:21 UTC
